# Using GitHub Actions, Build docker image, and push to Github Packages
name: Build and Push Docker Image
on:
  push:
    branches:
      - develop

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Build image
        run: docker build . -f Dockerfile -t ${{ github.repository }}:${{ github.sha }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push ${{ github.repository }}:${{ github.sha }}

